Implemented basic tests for headless detection
infosimples/detect-headless pull request #1
Opened 2018-09-20 16:45 UTC by brunonishimoto

### Description
Implemented basic tests for headless detection based on several sites included at [Trello](https://trello.com/c/hp0YBpri/1-detect-headless-p%C3%A1gina-que-testa-se-o-browser-%C3%A9-headless).

### Tests

- **User Agent:** in a browser running with `puppeteer` in headless mode, user agent includes `Headless`.
- **Plugins:** headless browsers don't have any plugins. So we can say that if it has plugin it's headful, but not otherwise since some browsers, like Firefox, don't have default plugins.
- **Languages:** all headful browser has at least one language. So we can say that if it has no language it's headless.
- **Webdriver:** this property is true when running in a headless browser.
- **Time elapse:** it pops an `alert()` on page and if it's closed too fast, means that it's headless.
- **Chrome element:** it's specific for `chrome` browser that has a element `window.chrome`.
- **Permission:** in headless mode `Notification.permission` and `navigator.permissions.query` report contradictory values.
- **Devtool:** `puppeteer` works on `devtools protocol`, this test checks if `devtool` is present or not.

2018-09-24 16:05 UTC, cezar-lima commented on index.html
> +      <tr>
It would be better to generate the table rows dynamically

2018-09-24 16:05 UTC, cezar-lima commented on scripts/detect_headless.js
> +/* This is a generic function that verify if the browswer is headless or not
Maybe it is better to use constants for results. This way it's easier to understand each function return.
```javascript
const HEADLESS = 1;
const UNDEFINED = 0;
const HEADFULL = -1;
```

2018-09-24 16:05 UTC, cezar-lima commented on scripts/detect_headless.js
> + * @param testFunction (function): funtion that checks if the browser si headless or not
Typos:
- `funtion` => `function`
- `si` => `is`

2018-09-24 16:05 UTC, cezar-lima commented on scripts/detect_headless.js
> + * @param resultFunction (function): function that assigns to the result block in HTML
This `@param` is not present

2018-09-24 16:05 UTC, cezar-lima commented on scripts/detect_headless.js
> +  let agent = navigator.userAgent
Missing `;`. According to file pattern. (many places)

2018-09-24 16:05 UTC, cezar-lima commented on scripts/detect_headless.js
> +  return /Headless/.test(agent);
It would be better to test with case insensitive regex

2018-09-24 16:05 UTC, cezar-lima commented on scripts/detect_headless.js
> +  return length === 0 ? '-1' : '0';
Use integer numbers instead strings

2018-09-24 16:05 UTC, cezar-lima commented on scripts/detect_headless.js
> +    resultBlock.innerHTML = `Webdriver present`
Use `""` or `''` when there is no interpolation (many places)

2018-09-24 16:05 UTC, cezar-lima commented on scripts/detect_headless.js
> +  resultBlock.innerHTML = `Time elapsed: ${elapse} (${signal} 30)`;
Use a more explicit description

2018-09-24 16:05 UTC, cezar-lima commented on scripts/detect_headless.js
> +    resultBlock.innerHTML = `Object navigator.permissions is undefined`
Why this condition sets resultBlock directly?

2018-09-24 16:05 UTC, cezar-lima commented on scripts/detect_headless.js
> +for (var i = 0; i < tests.length ; i++) {
Use `tests.forEach(test => {...})`

2018-09-24 16:23 UTC, brunonishimoto commented on scripts/detect_headless.js
> +    resultBlock.innerHTML = `Object navigator.permissions is undefined`
This is because one of the browser (I don't remember which one is) doesn't have the attribute `navigator.permissions`. But here,  it's better to call the function `permissionWriteResult` with one more parameter, right?

2018-09-24 16:37 UTC, cezar-lima commented on scripts/detect_headless.js
> +    resultBlock.innerHTML = `Object navigator.permissions is undefined`
Yes, this way you keep the pattern you've used in the others functions

2018-09-25 18:39 UTC, cezar-lima requested changes

2018-09-25 18:39 UTC, cezar-lima commented on scripts/detect_headless.js
> +  let connectionRtt = navigator.connection.rtt;
If `navigator` does not have `connection` attribute it calling `navigator.connection.rtt` throws an exception.
Check if `navigator.connection` isn't `undefined` before calling `.rtt`

2018-09-25 18:39 UTC, cezar-lima commented on scripts/detect_headless.js
> +function writeToBlock(block, text) {
Good, the code is cleaner without all the `writeResult` functions

2018-09-25 19:00 UTC, cezar-lima approved these changes

2018-09-25 19:00 UTC, merged